import { useEffect, useState } from 'react'
import { updateComponent, type ComponentVariant } from '../../api/catalog'
import { Botao } from '../../components/ui'
import './VariantEditDrawer.css'

export function VariantEditDrawer({ variant, onClose, onSaved }: { variant: ComponentVariant | null; onClose: () => void; onSaved: () => Promise<void> }) {
  const [descriptor, setDescriptor] = useState(''); const [description, setDescription] = useState(''); const [sku, setSku] = useState(''); const [price, setPrice] = useState(''); const [reason, setReason] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  useEffect(() => { if (!variant) return; setDescriptor(variant.descriptor ?? ''); setDescription(variant.description ?? ''); setSku(variant.sku ?? ''); setPrice(variant.price ? String(variant.price.amount) : ''); setReason(''); setError('') }, [variant])
  if (!variant) return null
  const save = async () => { if (!reason.trim()) return; setSaving(true); setError(''); try { const amount = price.trim() ? Number(price.replace(',', '.')) : NaN; if (price.trim() && (Number.isNaN(amount) || amount < 0)) { setError('Informe um preço válido.'); return } await updateComponent(variant.component_variant_id, { descriptor: descriptor || null, description: description || null, sku: sku ? { code: sku } : null, price: price.trim() ? { amount, currency: variant.price?.currency ?? 'BRL' } : null, change_reason: reason.trim() }); await onSaved(); onClose() } catch (err) { setError(err instanceof Error ? err.message : 'Não foi possível salvar a alteração.') } finally { setSaving(false) } }
  return <div className="variant-drawer-backdrop" role="presentation"><aside className="variant-drawer" role="dialog" aria-modal="true" aria-label="Editar variação"><header><div><span className="eyebrow">Editar variação</span><h2>{variant.component}</h2></div><button onClick={onClose} aria-label="Fechar">×</button></header><div className="variant-drawer-body"><p className="helper-text">SKU atual: {variant.sku ?? '—'} · {variant.dimension?.raw_label ?? 'sem dimensão'}</p><label>Descritor<input value={descriptor} onChange={(event) => setDescriptor(event.target.value)} /></label><label>Descrição<input value={description} onChange={(event) => setDescription(event.target.value)} /></label><label>SKU<input value={sku} onChange={(event) => setSku(event.target.value)} /></label><label>Preço (BRL)<input inputMode="decimal" value={price} onChange={(event) => setPrice(event.target.value)} /></label><label className="variant-reason">Motivo da alteração *<textarea value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Explique o que mudou e por quê." /></label>{error && <p className="feedback-error">{error}</p>}</div><footer><Botao variante="secundario" onClick={onClose}>Cancelar</Botao><Botao disabled={!reason.trim() || saving} onClick={() => void save()}>{saving ? 'Salvando…' : 'Salvar alteração'}</Botao></footer></aside></div>
}
