import { useEffect, useState } from 'react'
import { searchComponents, type ComponentVariant } from '../../../api/catalog'
import { addComponent, removeComponent, removeItem, swapComponent, type QuoteItem, type QuoteItemComponent } from '../../../api/quotes'
import { Botao, ConfirmDialog } from '../../../components/ui'

export function CompositionDrawer({ quoteId, item, onClose, onChanged }: { quoteId: number; item: QuoteItem | null; onClose: () => void; onChanged: () => Promise<void> }) {
  const [query, setQuery] = useState(''); const [results, setResults] = useState<ComponentVariant[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState<number | null>(null); const [replaceTarget, setReplaceTarget] = useState<QuoteItemComponent | null>(null); const [replacement, setReplacement] = useState<ComponentVariant | null>(null); const [removeLine, setRemoveLine] = useState(false)
  useEffect(() => { if (!item) return; const timer = window.setTimeout(() => { setLoading(true); void searchComponents({ q: query || undefined, page_size: 24 }).then((result) => setResults(result.items)).catch(() => setError('Não foi possível buscar peças.')).finally(() => setLoading(false)) }, 300); return () => window.clearTimeout(timer) }, [item, query])
  if (!item) return null
  const add = async (variant: ComponentVariant) => { setBusy(variant.component_variant_id); setError(''); try { await addComponent(quoteId, item.id, { component_variant_id: variant.component_variant_id }); await onChanged() } catch (err) { setError(err instanceof Error ? err.message : 'A peça não é compatível com esta composição.') } finally { setBusy(null) } }
  const remove = async (componentId: number) => { if (item.components.length === 1) { setRemoveLine(true); return }; setBusy(componentId); try { await removeComponent(quoteId, item.id, componentId); await onChanged() } catch (err) { setError(err instanceof Error ? err.message : 'Não foi possível remover a peça.') } finally { setBusy(null) } }
  const confirmRemoveLine = async () => { setBusy(item.id); try { await removeItem(quoteId, item.id); setRemoveLine(false); await onChanged(); onClose() } catch (err) { setError(err instanceof Error ? err.message : 'Não foi possível remover a linha.') } finally { setBusy(null) } }
  const confirmSwap = async () => { if (!replaceTarget || !replacement) return; setBusy(replaceTarget.id); try { await swapComponent(quoteId, item.id, replaceTarget.id, { component_variant_id: replacement.component_variant_id }); setReplaceTarget(null); setReplacement(null); await onChanged() } catch (err) { setError(err instanceof Error ? err.message : 'A nova peça não é compatível.') } finally { setBusy(null) } }
  const swapDescription = replaceTarget && replacement?.price ? `A peça atual está congelada em R$ ${replaceTarget.frozen_unit_price.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}. A nova peça será congelada em R$ ${replacement.price.amount.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}.` : 'A peça atual será substituída e o preço congelado da nova peça passará a valer neste orçamento.'
  return <div className="composition-drawer-backdrop"><aside className="composition-drawer" role="dialog" aria-modal="true" aria-label="Editar composição"><header><div><span className="eyebrow">Composição do item</span><h2>{item.label}</h2></div><button onClick={onClose}>×</button></header><section><h3>Peças já adicionadas · {item.components.length}</h3>{item.components.map((component) => <div className="composition-added" key={component.id}><span><b>{component.component ?? 'Peça'}</b><small>{component.sku ?? 'Sem SKU'}</small></span><Botao tamanho="sm" variante="fantasma" onClick={() => setReplaceTarget(component)}>Trocar</Botao><Botao tamanho="sm" variante="fantasma" disabled={busy === component.id} onClick={() => void remove(component.id)}>Remover</Botao></div>)}</section><section><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar peça, SKU ou acabamento…" /><h3>{replaceTarget ? `Escolha a substituição para ${replaceTarget.component ?? 'a peça'}` : loading ? 'Buscando…' : 'Peças disponíveis'}</h3>{results.map((variant) => <div className="composition-result" key={variant.component_variant_id}><span><b>{variant.component}{variant.descriptor ? ` · ${variant.descriptor}` : ''}</b><small>{variant.sku ?? 'Sem SKU'} · {variant.price ? `R$ ${variant.price.amount.toFixed(2)}` : 'Sem preço'}</small></span><Botao tamanho="sm" disabled={!variant.price || busy === variant.component_variant_id} onClick={() => replaceTarget ? setReplacement(variant) : void add(variant)}>{replaceTarget ? 'Selecionar' : 'Adicionar'}</Botao></div>)}</section>{error && <p className="feedback-error">{error}</p>}<footer><Botao variante="secundario" onClick={onClose}>Concluir</Botao></footer></aside><ConfirmDialog aberta={Boolean(replacement)} titulo="Trocar e recongelar preço?" descricao={swapDescription} confirmarLabel="Trocar peça" tom="primario" onConfirmar={() => void confirmSwap()} onFechar={() => setReplacement(null)} /><ConfirmDialog aberta={removeLine} titulo="Remover item inteiro?" descricao="Esta é a última peça da linha. Para removê-la, o item inteiro será excluído do orçamento." confirmarLabel="Remover item" onConfirmar={() => void confirmRemoveLine()} onFechar={() => setRemoveLine(false)} /></div>
}
