import { useEffect, useState } from 'react'
import { Link, Outlet, useNavigate, useOutletContext, useParams } from 'react-router-dom'
import { freezeTotals, updateItem, updateQuoteSettings, updateQuoteStatus, type QuoteTotals } from '../../../api/quotes'
import { getSettings, type AppSettings } from '../../../api/settings'
import { Botao, Card, Esqueleto, Selo } from '../../../components/ui'
import { STATUS_LABEL, STATUS_TOM } from '../../../labels'
import { useOrcamento, type OrcamentoData } from './useOrcamento'
import '../../painel/PainelPage.css'

export function EditorLayout() {
  const { id = '' } = useParams(); const data = useOrcamento(Number(id)); const { quote, quoteId, items, loading, error } = data; const navigate = useNavigate()
  if (loading) return <div className="page"><Esqueleto linhas={6} /></div>
  if (!quote) return <div className="page"><p className="feedback-error">{error ?? 'Orçamento não encontrado.'}</p></div>
  return <div className="editor"><header className="editor-head"><div><Link to="/orcamentos">← Orçamentos</Link><span className="eyebrow">{quote.quote_number} · {quote.valid_until ? `válido até ${quote.valid_until}` : 'sem validade'}</span><h1>{quote.customer.name} <Selo tom={STATUS_TOM[quote.status]}>{STATUS_LABEL[quote.status]}</Selo></h1></div><div><Botao variante="secundario" onClick={() => navigate(`/orcamentos/${quoteId}/documento`)}>Pré-visualizar</Botao>{quote.status === 'rascunho' && <Botao onClick={() => navigate('revisao')}>Revisar e enviar</Botao>}</div></header><nav className="editor-steps"><Link to="itens">1 Cliente ✓</Link><Link to="itens">2 Itens ({items.length})</Link><Link to="condicoes">3 Condições comerciais</Link><Link to="revisao">4 Revisar e enviar</Link></nav><Outlet context={data} /></div>
}

function useData() { return useOutletContext<OrcamentoData>() }

function Money({ value }: { value: number }) { return <>R$ {value.toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</> }
function Summary({ totals, checklist }: { totals: QuoteTotals; checklist: OrcamentoData['checklist'] }) { return <aside><Card title="Resumo ao vivo"><dl><dt>Subtotal</dt><dd><Money value={totals.subtotal} /></dd>{totals.item_discount_amount + totals.quote_discount_amount > 0 && <><dt>Descontos</dt><dd>− <Money value={totals.item_discount_amount + totals.quote_discount_amount} /></dd></>}<dt>Total</dt><dd><strong><Money value={totals.total} /></strong></dd>{totals.installment_count > 1 && <><dt>{totals.installment_count}× {totals.installment_interest_percent ? 'com juros' : 'sem juros'}</dt><dd><Money value={totals.installment_value} /></dd></>}</dl></Card>{checklist && <Card title="Falta para enviar"><p>{checklist.items.filter((item) => item.ok).length} de {checklist.items.length} verificações concluídas</p>{checklist.items.map((item) => <p key={item.code}>{item.ok ? '✓' : '○'} {item.label}</p>)}</Card>}</aside> }

export function EditorItemsPage() {
  const { quote, quoteId, items, totals, checklist, recarregar } = useData(); const [busy, setBusy] = useState<number | null>(null)
  if (!quote || !totals) return null
  async function changeQuantity(itemId: number, quantity: number) { if (quantity < 1) return; setBusy(itemId); try { await updateItem(quoteId, itemId, { quantity }); await recarregar() } finally { setBusy(null) } }
  return <div className="editor-body"><section><div className="items-title"><h2>{items.length} {items.length === 1 ? 'item' : 'itens'} no orçamento</h2>{quote.status === 'rascunho' && <Link className="add-item" to="/catalogo">+ Adicionar item</Link>}</div>{items.length === 0 ? <Card><p>Nenhum item adicionado. Consulte o catálogo para montar a proposta.</p></Card> : <div className="item-cards">{items.map((item) => <Card key={item.id} className="item-card"><header><span className={`piece-count${item.missing_required_components.length ? ' piece-count--error' : ''}`}>{item.components.length}pç</span><span><b>{item.label}</b><small>{item.missing_required_components.length ? `Falta: ${item.missing_required_components.join(', ')}` : item.components.length > 1 ? 'Produto montado' : 'Item avulso'}</small></span><div className="item-quantity"><Botao tamanho="sm" variante="secundario" disabled={busy === item.id || quote.status !== 'rascunho'} onClick={() => void changeQuantity(item.id, item.quantity - 1)}>−</Botao><b>{item.quantity}</b><Botao tamanho="sm" variante="secundario" disabled={busy === item.id || quote.status !== 'rascunho'} onClick={() => void changeQuantity(item.id, item.quantity + 1)}>+</Botao></div><strong><Money value={item.line_subtotal} /></strong></header>{item.components.length > 1 && <footer>{item.components.map((component) => <p key={component.id}><span>{component.component ?? 'Peça'} · {component.description ?? component.descriptor ?? 'sem descrição'}</span><span className="mono">{component.sku ?? '—'}</span><span className="mono"><Money value={component.frozen_unit_price} /></span></p>)}<small>PREÇO CONGELADO · não muda se o catálogo for atualizado</small></footer>}</Card>)}</div>}</section><Summary totals={totals} checklist={checklist} /></div>
}

export function EditorConditionsPage() {
  const { quote, quoteId, totals, checklist, recarregar } = useData(); const [settings, setSettings] = useState<AppSettings | null>(null); const [markup, setMarkup] = useState(''); const [usesGlobal, setUsesGlobal] = useState(true); const [discountMode, setDiscountMode] = useState<'none' | 'percent' | 'amount'>('none'); const [discount, setDiscount] = useState(''); const [reason, setReason] = useState(''); const [installments, setInstallments] = useState('1'); const [interest, setInterest] = useState('0'); const [entradaMode, setEntradaMode] = useState<'none' | 'amount' | 'percent'>('none'); const [entrada, setEntrada] = useState(''); const [saving, setSaving] = useState(false)
  useEffect(() => { void getSettings().then(setSettings) }, []); useEffect(() => { if (!quote) return; setMarkup(String(quote.markup_percent)); setUsesGlobal(quote.markup_uses_global); setDiscountMode(quote.quote_discount_percent != null ? 'percent' : quote.quote_discount_amount != null ? 'amount' : 'none'); setDiscount(String(quote.quote_discount_percent ?? quote.quote_discount_amount ?? '')); setReason(quote.quote_discount_reason ?? ''); setInstallments(String(quote.installment_count)); setInterest(String(quote.installment_interest_percent)); setEntradaMode(quote.entrada_percent ? 'percent' : quote.entrada_amount ? 'amount' : 'none'); setEntrada(String(quote.entrada_percent || quote.entrada_amount || '')) }, [quote])
  if (!quote || !totals) return null
  const needsReason = discountMode === 'percent' && Number(discount) > (settings?.discount_limit_percent ?? 8)
  async function save() { if (needsReason && !reason.trim()) return; setSaving(true); try { await updateQuoteSettings(quoteId, { markup_uses_global: usesGlobal, markup_percent: usesGlobal ? undefined : Number(markup) || 0, quote_discount_percent: discountMode === 'percent' ? Number(discount) || 0 : null, quote_discount_amount: discountMode === 'amount' ? Number(discount) || 0 : null, quote_discount_reason: reason || null, installment_count: Math.max(1, Number(installments) || 1), installment_interest_percent: Number(interest) || 0, entrada_amount: entradaMode === 'amount' ? Number(entrada) || 0 : null, entrada_percent: entradaMode === 'percent' ? Number(entrada) || 0 : null }); await recarregar() } finally { setSaving(false) } }
  return <div className="editor-body"><section className="conditions"><Card title="Margem de venda"><p>Aplicada sobre o custo congelado. O padrão da empresa é {settings?.global_markup_percent ?? '…'}%.</p><label><input type="radio" checked={usesGlobal} onChange={() => setUsesGlobal(true)} /> Padrão da empresa</label><label><input type="radio" checked={!usesGlobal} onChange={() => setUsesGlobal(false)} /> Margem específica <input type="number" disabled={usesGlobal} value={markup} onChange={(e) => setMarkup(e.target.value)} /> %</label></Card><Card title="Desconto"><div className="field-row"><select value={discountMode} onChange={(e) => setDiscountMode(e.target.value as typeof discountMode)}><option value="none">Nenhum</option><option value="percent">Percentual</option><option value="amount">Valor R$</option></select>{discountMode !== 'none' && <input type="number" value={discount} onChange={(e) => setDiscount(e.target.value)} placeholder={discountMode === 'percent' ? '%' : 'R$'} />}<input value={reason} onChange={(e) => setReason(e.target.value)} placeholder="Motivo (fica no histórico)" /></div>{needsReason && <p className="feedback-warning">Acima da alçada de {settings?.discount_limit_percent ?? 8}%; informe o motivo.</p>}</Card><Card title="Pagamento"><div className="field-row"><label>Entrada <select value={entradaMode} onChange={(e) => setEntradaMode(e.target.value as typeof entradaMode)}><option value="none">Sem entrada</option><option value="amount">R$</option><option value="percent">%</option></select></label>{entradaMode !== 'none' && <input type="number" value={entrada} onChange={(e) => setEntrada(e.target.value)} />}<label>Parcelas <input type="number" min="1" value={installments} onChange={(e) => setInstallments(e.target.value)} /></label>{Number(installments) > 1 && <label>Juros % <input type="number" min="0" value={interest} onChange={(e) => setInterest(e.target.value)} /></label>}</div></Card><Botao disabled={saving || (needsReason && !reason.trim())} onClick={() => void save()}>{saving ? 'Salvando…' : 'Salvar condições'}</Botao></section><Summary totals={totals} checklist={checklist} /></div>
}

export function EditorReviewPage() { const { quoteId, quote, totals, checklist } = useData(); const navigate = useNavigate(); const [busy, setBusy] = useState(false); if (!quote || !totals || !checklist) return null; async function send() { setBusy(true); try { await freezeTotals(quoteId); await updateQuoteStatus(quoteId, 'enviado'); navigate('/orcamentos') } finally { setBusy(false) } } return <div className="editor-body"><Card title={checklist.ready ? 'Pronto para enviar' : 'Faltam verificações'}>{checklist.items.map((item) => <p key={item.code}>{item.ok ? '✓' : '○'} <b>{item.label}</b>{!item.ok && ` — ${item.pendencias.join('; ')}`}</p>)}<Botao disabled={!checklist.ready || busy} onClick={() => void send()}>{busy ? 'Enviando…' : 'Congelar e enviar'}</Botao></Card><Summary totals={totals} checklist={checklist} /></div> }
